# Generated by Django 5.0.6 on 2024-06-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grades",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grades",
            name="explanation",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="grades",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grades",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="grades",
            name="subject",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Math"),
                    ("l", "literature"),
                    ("s", "Sport"),
                    ("b", "Biology"),
                    ("h", "History"),
                ],
                default="m",
                max_length=1,
            ),
        ),
    ]
