# Generated by Django 5.0.6 on 2024-07-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_rename_message_contact_msg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tsk_due_date", models.DateTimeField()),
                ("subject", models.TextField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("s", "Started"),
                            ("t", "On Track"),
                            ("b", "Behind"),
                            ("o", "Open"),
                            ("c", "Closed"),
                        ],
                        default="o",
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("close_date", models.DateTimeField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
