# Generated by Django 5.0.6 on 2024-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="close_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="tsk_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
